### ISSUE TITLE
سایت هایی که یوزر های ایرانی رو بن کردن 

### ISSUE THREAD

**Issue by mohamadfarahani** [hiddify/filterchi_report#4]
وقتی یوزر فیلتر شکن میزنه انتظار داره وقتی میره تو یه سایتی ایپی ایرانش مشخص نشه و با اعتماد به اینکه ایپیش ایران نیست یوزر میتونه خودشو توی خیلی از سایت ها (مخصوصا سایت های مالی) که فیلتر نیستن و صرفا با ایپی ایران مشکل دارن به خطر بن شدن بندازه

**Comment by hiddify-com** [comment]
یه سری لیست در آوردیم
ولی این انتخاب کاربره که برای چه منظوری میخواد استفاده کنه دیگه
